name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed for pushing to GHCR

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Download dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...

    - name: Build CLI
      run: go build -o obscure .

    - name: Decode Firebase service account key
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_B64 }}" | base64 -d > firebase-key.json
        echo "FIREBASE_CREDENTIALS=$(pwd)/firebase-key.json" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/shah1011/obscure-cli:latest .

    - name: Push Docker image
      run: |
        docker push ghcr.io/shah1011/obscure-cli:latest
